package executor

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/weimengtsgit/xian630/factory-server/internal/model"
	"github.com/weimengtsgit/xian630/factory-server/internal/runner"
	"github.com/weimengtsgit/xian630/factory-server/internal/store"
)

type fakeClaudeCommand struct {
	t         *testing.T
	workspace string
	output    map[string]any
}

func (f fakeClaudeCommand) Run(_ context.Context, dir string, name string, args ...string) (runner.CommandResult, error) {
	return f.run(dir, name, args...)
}

func (f fakeClaudeCommand) RunWithInput(_ context.Context, dir string, _ string, name string, args ...string) (runner.CommandResult, error) {
	return f.run(dir, name, args...)
}

func (f fakeClaudeCommand) run(dir string, name string, args ...string) (runner.CommandResult, error) {
	if name == "git" {
		return runner.CommandResult{ExitCode: 0}, nil
	}
	if name != "claude" {
		f.t.Fatalf("command name = %q, want claude or git", name)
	}
	if len(args) == 0 || args[0] != "--print" {
		f.t.Fatalf("claude args = %v, want --print invocation", args)
	}
	raw, err := json.MarshalIndent(f.output, "", "  ")
	if err != nil {
		f.t.Fatalf("marshal output: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "output.json"), raw, 0o644); err != nil {
		f.t.Fatalf("write output.json: %v", err)
	}
	if projectDir, _ := f.output["projectDir"].(string); projectDir != "" {
		appDir := filepath.Join(f.workspace, projectDir)
		if err := os.MkdirAll(filepath.Join(appDir, ".factory"), 0o755); err != nil {
			f.t.Fatalf("mkdir app factory: %v", err)
		}
		manifest := `{
  "schemaVersion": 1,
  "slug": "demo",
  "name": "Demo Generated App",
  "type": "timeline-replay",
  "source": "generated",
  "description": "generated by test",
  "entry": "static-vite",
  "path": "generated-apps/demo",
  "build": {"command": "npm run build", "outputDir": "dist"},
  "docker": {"enabled": true, "dockerfile": "Dockerfile", "context": ".", "runtimePort": 80}
}`
		if err := os.WriteFile(filepath.Join(appDir, ".factory", "app.json"), []byte(manifest), 0o644); err != nil {
			f.t.Fatalf("write manifest: %v", err)
		}
	}
	return runner.CommandResult{ExitCode: 0, Stdout: "ok"}, nil
}

func newClaudeRunnerTestStore(t *testing.T) *store.Store {
	t.Helper()
	st, err := store.Open(":memory:")
	if err != nil {
		t.Fatalf("open store: %v", err)
	}
	t.Cleanup(func() { _ = st.Close() })
	return st
}

func claudeJobStep(kind model.StepKind) (model.Job, model.JobStep) {
	now := time.Now()
	return model.Job{
			ID:              "job_claude_1",
			UserPrompt:      "生成一个航母编队近一个月航行轨迹和事件的东海地图复盘应用",
			Status:          model.JobStatusRunning,
			CurrentStepKind: kind,
			CreatedAt:       now,
			UpdatedAt:       now,
		}, model.JobStep{
			ID:      "step_" + string(kind),
			JobID:   "job_claude_1",
			Kind:    kind,
			Seq:     1,
			Status:  model.StepStatusRunning,
			Attempt: 1,
		}
}

func TestClaudeStepRunnerRegistersGeneratedAppFromCodeGenerationOutput(t *testing.T) {
	st := newClaudeRunnerTestStore(t)
	ws := t.TempDir()
	cmd := fakeClaudeCommand{
		t:         t,
		workspace: ws,
		output: map[string]any{
			"projectDir":     "generated-apps/demo",
			"createdFiles":   []string{"generated-apps/demo/.factory/app.json"},
			"needsUserInput": false,
			"questions":      []any{},
		},
	}
	r := &ClaudeStepRunner{
		Store:        st,
		Workspace:    ws,
		ArtifactRoot: filepath.Join(ws, ".factory-runs"),
		Claude:       &runner.ClaudeRunner{Runner: cmd},
		AuditRunner:  cmd,
	}
	job, step := claudeJobStep(model.StepCodeGeneration)
	if err := st.CreateJob(context.Background(), job); err != nil {
		t.Fatalf("create job: %v", err)
	}

	res, err := r.Run(context.Background(), job, step)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if res.Status != model.StepStatusSucceeded {
		t.Fatalf("status = %s (%s/%s), want succeeded", res.Status, res.ErrorCode, res.ErrorMessage)
	}
	app, err := st.GetApplication(context.Background(), "app-demo")
	if err != nil || app == nil {
		t.Fatalf("GetApplication app-demo = %#v, %v", app, err)
	}
	if app.Name != "Demo Generated App" || app.Path != "generated-apps/demo" {
		t.Fatalf("app = %#v", app)
	}
	updated, _ := st.GetJob(context.Background(), job.ID)
	if updated.CreatedAppID != "app-demo" || updated.AppSlug != "demo" || updated.AppName != "Demo Generated App" {
		t.Fatalf("job app linkage = %#v", updated)
	}
}

func TestClaudeStepRunnerReturnsWaitingUserWhenOutputAsksClarification(t *testing.T) {
	st := newClaudeRunnerTestStore(t)
	ws := t.TempDir()
	cmd := fakeClaudeCommand{
		t:         t,
		workspace: ws,
		output: map[string]any{
			"summary":        "需要澄清",
			"appType":        "timeline-replay",
			"needsUserInput": true,
			"questions": []map[string]string{
				{"id": "range", "question": "时间范围是否固定为近一个月？", "defaultAnswer": "是"},
			},
		},
	}
	r := &ClaudeStepRunner{
		Store:        st,
		Workspace:    ws,
		ArtifactRoot: filepath.Join(ws, ".factory-runs"),
		Claude:       &runner.ClaudeRunner{Runner: cmd},
		AuditRunner:  cmd,
	}
	job, step := claudeJobStep(model.StepRequirementAnalysis)

	res, err := r.Run(context.Background(), job, step)
	if err != nil {
		t.Fatalf("Run: %v", err)
	}
	if res.Status != model.StepStatusWaitingUser || !res.NeedsUserInput {
		t.Fatalf("result = %#v, want waiting_user with needs input", res)
	}
}
