js_import ops from /etc/nginx/ops-store-api.js;

server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 1m;

    location = /api/apps {
        js_content ops.apps;
    }

    location ~ ^/api/apps/.+ {
        js_content ops.apps;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /health {
        access_log off;
        return 200 "OK";
    }
}
